import PropTypes from 'prop-types'
import { useState } from 'react'

/**
 * Relevant classes from _dropdown.scss include
 * --------------------------------------------
 * 
 *  activator - add class isDropped to drop the panel
 * 
 *  The rest are handled by the Dropdown component, but
 *  these include:
 * 
 *  isDropped - class added to the activator and
 *  placeholder when the panel is dropped
 * 
 *  activation_panel - the panel to be dropped.
 *      Children sent by prop will go here
 * 
 *  activation_panel--animated - a workhorse class to
 *      help the animation function
 * 
 *  placeholder - generated by the Dropdown component
 *      automatically. Generates space for the
 *      dropped down content
 * 
 *  style_rotate_X - the default appearance style of
 *      the dropped down component. Also includes
 *      a keyframes called rotateMenu
 */

const Dropdown = ({ children }) => {

    const [ isDroppedContent, setIsDroppedContent ] = useState('')

    function handleDropContent() {
        setIsDroppedContent( isDroppedContent === '' ?
            ' isDropped'
            : ''
        )
    }

    return (
        <>
            <section className={`activator${isDroppedContent}`} onClick={handleDropMenu}>
                <h3>Content issues</h3>
                <article className="activation_panel activation_panel--animated style_rotate_X">
                    {children}
                </article>
            </section>
            <article aria-hidden='true' className={`placeholder${isDroppedContent}`}>
                {children}
            </article>            
        </>
    )
}

Dropdown.propTypes = {
    children: PropTypes.element
}

export default Dropdown